name: Android CI
on: [push, pull_request]
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: ls -la



git add .
git commit -m "feat: initial Compose app (Hello Oshilife)"
git push -u origin feature/compose-room-mvp
